import type { Prisma } from "@prisma/client";

type AgendaMeeting = Prisma.MeetingGetPayload<{
  include: {
    club: {
      include: {
        centre: true;
      };
    };
    roleSlots: {
      include: {
        roleDefinition: true;
        assignedStudent: {
          include: {
            user: true;
          };
        };
      };
    };
  };
}>;

export function buildAgendaRtf(meeting: AgendaMeeting) {
  const roleSlots = [...meeting.roleSlots].sort((left, right) => left.sortOrder - right.sortOrder);
  const assignmentRows = roleSlots.map((slot) => tableRow([
    slot.roleDefinition.name,
    assignedMemberName(slot),
    rolePreparationNote(slot.roleDefinition.name),
    slot.assignedStudentId ? "Assigned" : "Open for member sign-up"
  ])).join("");
  const agendaRows = agendaSectionsForTemplate(meeting.templateType)
    .flatMap((section) => [
      sectionHeaderRow(section.offset, section.title),
      ...section.items.map((item) => tableRow([
        item.duration,
        item.activity,
        item.roles.map((roleName) => `${roleName}: ${assignedMemberForRole(roleSlots, roleName)}`).join("; ") || "All members",
        item.notes
      ]))
    ])
    .join("");

  return [
    "{\\rtf1\\ansi\\deff0",
    "{\\fonttbl{\\f0 Arial;}{\\f1 Garamond;}}",
    "\\viewkind4\\uc1\\paperw12240\\paperh15840\\margl1080\\margr1080\\margt900\\margb900\\pard\\f0\\fs24",
    heading("iLEAP Club Meeting Agenda", 34),
    paragraph(`MEETING DATE: ${formatDate(meeting.meetingDate)}`),
    paragraph(`SESSION: ${meeting.startTime}`),
    paragraph(`CLUB: ${meeting.club.name}`),
    paragraph(`CENTRE: ${meeting.club.centre.name}`),
    paragraph(`LOCATION / ONLINE LINK: ${meeting.location || "To be confirmed"}`),
    paragraph(`TEMPLATE: ${meeting.templateType}`),
    "\\par",
    heading("Meeting Flow", 28),
    tableHeader(["Time", "Agenda Item", "Lead / Member", "Notes"]),
    agendaRows,
    "\\par",
    heading("Member Role Sign-Up", 28),
    tableHeader(["Role", "Assigned Member", "Preparation Notes", "Signup Status"]),
    assignmentRows || tableRow(["No roles configured", "Open", "Add role slots before publishing the meeting agenda.", "Open"]),
    "\\par",
    heading("Facilitator Notes", 28),
    bullet("Open roles are available for eligible student members to claim until roles are locked."),
    bullet("Facilitators may override role assignments when a meeting needs balancing."),
    bullet("Members should review role expectations and prepare before the session starts."),
    "\\par",
    paragraph("Generated by iLEAP Club Member Portal"),
    "}"
  ].join("");
}

export function agendaFileName(meeting: Pick<AgendaMeeting, "title" | "meetingDate">) {
  const date = meeting.meetingDate.toISOString().slice(0, 10);
  const slug = meeting.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60) || "meeting-agenda";

  return `${date}-${slug}.rtf`;
}

function heading(value: string, size: number) {
  return `\\pard\\b\\fs${size} ${escapeRtf(value)}\\b0\\fs24\\par`;
}

function paragraph(value: string) {
  return `\\pard ${escapeRtf(value)}\\par`;
}

function bullet(value: string) {
  return `\\pard\\li360\\tx360\\bullet\\tab ${escapeRtf(value)}\\par`;
}

function tableHeader(values: string[]) {
  return tableRow(values, true);
}

function tableRow(values: string[], isHeader = false) {
  const [first, second, third, fourth] = values.map(escapeRtf);
  const boldStart = isHeader ? "\\b " : "";
  const boldEnd = isHeader ? "\\b0 " : "";

  return [
    "\\trowd\\trgaph108\\trleft0",
    "\\cellx1500\\cellx4500\\cellx7100\\cellx10000",
    `\\intbl ${boldStart}${first}${boldEnd}\\cell`,
    `\\intbl ${boldStart}${second}${boldEnd}\\cell`,
    `\\intbl ${boldStart}${third}${boldEnd}\\cell`,
    `\\intbl ${boldStart}${fourth || ""}${boldEnd}\\cell`,
    "\\row"
  ].join("");
}

function sectionHeaderRow(offset: string, title: string) {
  return tableRow([offset, title.toUpperCase(), "", ""], true);
}

function formatDate(value: Date) {
  return new Intl.DateTimeFormat("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC"
  }).format(value);
}

function escapeRtf(value: string) {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/{/g, "\\{")
    .replace(/}/g, "\\}")
    .replace(/\n/g, "\\par ");
}

type AgendaSection = {
  offset: string;
  title: string;
  items: AgendaItem[];
};

type AgendaItem = {
  duration: string;
  activity: string;
  roles: string[];
  notes: string;
};

type AgendaRoleSlot = AgendaMeeting["roleSlots"][number];

const regularMeetingSections: AgendaSection[] = [
  {
    offset: "+0 min",
    title: "Arrival and Agenda Changes",
    items: [
      { duration: "5 min", activity: "Arrival, seating, agenda changes", roles: ["Chair"], notes: "Confirm attendance and role coverage." }
    ]
  },
  {
    offset: "+5 min",
    title: "Introduction",
    items: [
      { duration: "2 min", activity: "Welcome remarks", roles: ["Chair"], notes: "Open the meeting and introduce the theme." },
      { duration: "2 min", activity: "Phrase or idiom of the day", roles: ["Grammarian"], notes: "Share the language focus for members to use." },
      { duration: "2 min", activity: "Filler word briefing", roles: ["Ah Counter"], notes: "Explain what will be tracked." },
      { duration: "2 min", activity: "Timing rules", roles: ["Timer"], notes: "Review timing signals and limits." },
      { duration: "2 min", activity: "Fine or quiz briefing", roles: ["Quiz Master", "Fine Master"], notes: "Explain participation challenge if used." }
    ]
  },
  {
    offset: "+10 min",
    title: "Speeches",
    items: [
      { duration: "2 min", activity: "Speaker introductions", roles: ["Chair"], notes: "Introduce each speaker and evaluator pair." },
      { duration: "4 min each", activity: "Prepared speeches", roles: ["Speaker 1", "Speaker 2", "Speaker 3", "Speaker 4"], notes: "Speakers present prepared projects." },
      { duration: "During speeches", activity: "Evaluator notes", roles: ["Evaluator 1", "Evaluator 2", "Evaluator 3", "Evaluator 4"], notes: "Evaluators listen for strengths and growth points." }
    ]
  },
  {
    offset: "+70 min",
    title: "Evaluations",
    items: [
      { duration: "2 min", activity: "Evaluation introduction", roles: ["Chair"], notes: "Transition from speeches to feedback." },
      { duration: "2 min each", activity: "Speaker evaluations", roles: ["Evaluator 1", "Evaluator 2", "Evaluator 3", "Evaluator 4"], notes: "Give specific, balanced feedback." },
      { duration: "2 min", activity: "Timer report", roles: ["Timer"], notes: "Report speaker and role timings." },
      { duration: "2 min", activity: "Grammarian report", roles: ["Grammarian"], notes: "Highlight effective language and word usage." },
      { duration: "2 min", activity: "Filler word report", roles: ["Ah Counter"], notes: "Report filler words and repeated phrases." }
    ]
  },
  {
    offset: "+105 min",
    title: "Closing",
    items: [
      { duration: "5 min", activity: "Closing thought and announcements", roles: ["Chair"], notes: "Recognize members, confirm next meeting, and close." }
    ]
  }
];

const debateMeetingSections: AgendaSection[] = [
  {
    offset: "+0 min",
    title: "Opening",
    items: [
      { duration: "5 min", activity: "Arrival, agenda changes, debate motion", roles: ["Chair", "Debate Moderator"], notes: "Confirm teams, rules, and speaking order." },
      { duration: "2 min", activity: "Timer briefing", roles: ["Timer"], notes: "Review signals for each debate segment." }
    ]
  },
  {
    offset: "+10 min",
    title: "Debate",
    items: [
      { duration: "4 min each", activity: "Opening arguments", roles: ["Speaker 1", "Speaker 2"], notes: "Each side presents its opening position." },
      { duration: "3 min each", activity: "Rebuttals", roles: ["Speaker 3", "Speaker 4"], notes: "Respond directly to the opposing argument." },
      { duration: "8 min", activity: "Audience questions", roles: ["Debate Moderator"], notes: "Moderate concise questions from members." },
      { duration: "5 min", activity: "Vote collection", roles: ["Vote Counter"], notes: "Collect and count member votes." }
    ]
  },
  {
    offset: "+45 min",
    title: "Evaluation and Closing",
    items: [
      { duration: "2 min each", activity: "Debate feedback", roles: ["Evaluator 1", "Evaluator 2"], notes: "Evaluate reasoning, delivery, and listening." },
      { duration: "5 min", activity: "Results and closing", roles: ["Chair", "Vote Counter"], notes: "Announce result and close the meeting." }
    ]
  }
];

const townHallMeetingSections: AgendaSection[] = [
  {
    offset: "+0 min",
    title: "Town Hall Setup",
    items: [
      { duration: "5 min", activity: "Arrival, agenda changes, scenario briefing", roles: ["Chair", "Town Hall Lead"], notes: "Introduce the leadership challenge." },
      { duration: "2 min", activity: "Timer briefing", roles: ["Timer"], notes: "Set speaking limits for proposals and responses." }
    ]
  },
  {
    offset: "+10 min",
    title: "Leadership Challenge",
    items: [
      { duration: "5 min", activity: "Problem statement", roles: ["Town Hall Lead"], notes: "Frame the decision members must solve." },
      { duration: "4 min each", activity: "Member proposals", roles: ["Speaker 1", "Speaker 2", "Speaker 3", "Speaker 4"], notes: "Present a clear recommendation with reasons." },
      { duration: "10 min", activity: "Moderated discussion", roles: ["Chair"], notes: "Invite questions and compare options." }
    ]
  },
  {
    offset: "+55 min",
    title: "Decision and Reflection",
    items: [
      { duration: "5 min", activity: "Vote or consensus", roles: ["Vote Counter"], notes: "Record the selected recommendation." },
      { duration: "2 min each", activity: "Leadership feedback", roles: ["Evaluator 1", "Evaluator 2"], notes: "Evaluate clarity, teamwork, and decision quality." },
      { duration: "5 min", activity: "Closing thought", roles: ["Chair"], notes: "Summarize lessons and next steps." }
    ]
  }
];

function agendaSectionsForTemplate(templateType: string) {
  const normalizedTemplate = normalize(templateType);

  if (normalizedTemplate.includes("debate")) {
    return debateMeetingSections;
  }

  if (normalizedTemplate.includes("townhall")) {
    return townHallMeetingSections;
  }

  return regularMeetingSections;
}

function assignedMemberName(slot: AgendaRoleSlot) {
  return slot.assignedStudent
    ? `${slot.assignedStudent.user.firstName} ${slot.assignedStudent.user.lastName}`
    : "Open";
}

function assignedMemberForRole(roleSlots: AgendaRoleSlot[], requestedRole: string) {
  const slot = roleSlots.find((candidate) => roleMatches(candidate.roleDefinition.name, requestedRole));

  return slot ? assignedMemberName(slot) : "Open";
}

function roleMatches(actualRole: string, requestedRole: string) {
  const actual = normalize(actualRole);
  const requested = normalize(requestedRole);
  const aliases = roleAliases[requested] ?? [requested];

  return aliases.some((alias) => actual === alias || actual.includes(alias));
}

function rolePreparationNote(roleName: string) {
  const normalizedRole = normalize(roleName);

  if (normalizedRole.includes("speaker")) {
    return "Prepare speech title, objective, and timing.";
  }

  if (normalizedRole.includes("evaluator")) {
    return "Listen for strengths, structure, delivery, and one clear growth point.";
  }

  if (normalizedRole.includes("timer")) {
    return "Prepare timing signals and final timing report.";
  }

  if (normalizedRole.includes("grammarian")) {
    return "Prepare phrase or idiom of the day and language notes.";
  }

  if (normalizedRole.includes("ahcounter") || normalizedRole.includes("filler")) {
    return "Track filler words and repeated phrases.";
  }

  if (normalizedRole.includes("chair")) {
    return "Prepare welcome, transitions, and closing remarks.";
  }

  return "Review the role expectations before the meeting.";
}

function normalize(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

const roleAliases: Record<string, string[]> = {
  ahcounter: ["ahcounter", "fillercounter", "ifillercounter"],
  finemaster: ["finemaster", "quizmaster"],
  quizmaster: ["quizmaster", "finemaster"],
  chair: ["chair", "ichair"],
  debatemoderator: ["debatemoderator"],
  townhalllead: ["townhalllead"]
};
