import type { Prisma } from "@prisma/client";

type AgendaMeeting = Prisma.MeetingGetPayload<{
  include: {
    club: {
      include: {
        centre: true;
      };
    };
    roleSlots: {
      include: {
        roleDefinition: true;
        assignedStudent: {
          include: {
            user: true;
          };
        };
      };
    };
  };
}>;

export function buildAgendaRtf(meeting: AgendaMeeting) {
  const title = "iLEAP Club Meeting Agenda";
  const rows = meeting.roleSlots
    .sort((left, right) => left.sortOrder - right.sortOrder)
    .map((slot) => {
      const assignedName = slot.assignedStudent
        ? `${slot.assignedStudent.user.firstName} ${slot.assignedStudent.user.lastName}`
        : "Open";

      return tableRow([
        slot.roleDefinition.name,
        assignedName,
        slot.slotLabel || `Role ${slot.sortOrder}`
      ]);
    })
    .join("");

  return [
    "{\\rtf1\\ansi\\deff0",
    "{\\fonttbl{\\f0 Arial;}}",
    "\\viewkind4\\uc1\\pard\\f0\\fs24",
    heading(title, 34),
    paragraph(`Club: ${meeting.club.name}`),
    paragraph(`Centre: ${meeting.club.centre.name}`),
    paragraph(`Meeting Date: ${formatDate(meeting.meetingDate)}`),
    paragraph(`Session Time: ${meeting.startTime}`),
    paragraph(`Location / Online Link: ${meeting.location || "To be confirmed"}`),
    paragraph(`Agenda Template: ${meeting.templateType}`),
    "\\par",
    heading("Role Assignments", 28),
    tableHeader(["Role", "Assigned Member", "Slot"]),
    rows || tableRow(["No roles configured", "Open", ""]),
    "\\par",
    heading("Meeting Notes", 28),
    bullet("Open roles should be filled before the meeting begins."),
    bullet("Facilitators may override assignments when needed."),
    bullet("Students should prepare for their assigned role in advance."),
    "\\par",
    paragraph("Generated by iLEAP Club Member Portal"),
    "}"
  ].join("");
}

export function agendaFileName(meeting: Pick<AgendaMeeting, "title" | "meetingDate">) {
  const date = meeting.meetingDate.toISOString().slice(0, 10);
  const slug = meeting.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60) || "meeting-agenda";

  return `${date}-${slug}.rtf`;
}

function heading(value: string, size: number) {
  return `\\pard\\b\\fs${size} ${escapeRtf(value)}\\b0\\fs24\\par`;
}

function paragraph(value: string) {
  return `\\pard ${escapeRtf(value)}\\par`;
}

function bullet(value: string) {
  return `\\pard\\li360\\tx360\\bullet\\tab ${escapeRtf(value)}\\par`;
}

function tableHeader(values: string[]) {
  return tableRow(values, true);
}

function tableRow(values: string[], isHeader = false) {
  const [first, second, third] = values.map(escapeRtf);
  const boldStart = isHeader ? "\\b " : "";
  const boldEnd = isHeader ? "\\b0 " : "";

  return [
    "\\trowd\\trgaph108\\trleft0",
    "\\cellx2500\\cellx5900\\cellx8200",
    `\\intbl ${boldStart}${first}${boldEnd}\\cell`,
    `\\intbl ${boldStart}${second}${boldEnd}\\cell`,
    `\\intbl ${boldStart}${third}${boldEnd}\\cell`,
    "\\row"
  ].join("");
}

function formatDate(value: Date) {
  return new Intl.DateTimeFormat("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC"
  }).format(value);
}

function escapeRtf(value: string) {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/{/g, "\\{")
    .replace(/}/g, "\\}")
    .replace(/\n/g, "\\par ");
}
